version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mercury_db
    environment:
      MYSQL_DATABASE: mercury
      MYSQL_ROOT_PASSWORD: mercury
    volumes:
      - db_data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    network_mode: host
  mercury:
    image: mercury:latest
    restart: always
    container_name: mercury
    volumes:
      - .env:/app/.env
      - /data:/data
      - /tmp:/tmp
    network_mode: host


volumes:
  db_data:
